export const articles = [
  // ── LP1（ブランド・世界観）──────────────────────────
  {
    slug: 'bath-beauty-habit',
    lp: 'lp1',
    title: 'お風呂時間を、\n"整う美容時間"へ。',
    catchphrase: 'お風呂時間を、\nもっと整う時間へ。',
    category: '美容習慣',
    tags: ['習慣化', '肌変化', 'バス美容'],
    heroImage: '/images/bath-scene.png',
    relatedSlugs: ['beauty-women-bath', 'bath-as-serum', 'effortless-bath-beauty'],
  },
  {
    slug: 'beauty-women-bath',
    lp: 'lp1',
    title: '美容意識の高い女性ほど、\nお風呂時間を大切にしている。',
    catchphrase: '美容を知る女性ほど、\nバスタイムにこだわる。',
    category: '美容ライフスタイル',
    tags: ['バスタイム', '美容習慣', 'セルフケア'],
    heroImage: '/images/morning-bath.png',
    relatedSlugs: ['bath-as-serum', 'bath-beauty-habit', 'effortless-bath-beauty'],
  },
  {
    slug: 'bath-as-serum',
    lp: 'lp1',
    title: '"浸かる美容液"という新習慣。',
    catchphrase: '"塗る"から"浸かる"へ。',
    category: 'トレンド美容',
    tags: ['浸かる美容液', '入浴剤', '全身スキンケア'],
    heroImage: '/images/bath-closeup.png',
    relatedSlugs: ['bath-beauty-habit', 'beauty-women-bath', 'moisturizing-bathsalt'],
  },

  // ── LP2（美肌・保湿）────────────────────────────────
  {
    slug: 'dry-skin-bathsalt',
    lp: 'lp2',
    title: '乾燥肌の人が、\n入浴剤選びで見るべきこと。',
    catchphrase: 'お湯の質が、\n乾燥肌の未来を変える。',
    category: '乾燥肌ケア',
    tags: ['乾燥肌', '入浴剤', 'シリカ'],
    heroImage: '/images/bath-scene-3.png',
    relatedSlugs: ['moisturizing-bathsalt', 'dry-after-bath', 'bath-vs-topical-skincare'],
  },
  {
    slug: 'moisturizing-bathsalt',
    lp: 'lp2',
    title: '保湿入浴剤を変えたら、\n夜が静かになった。',
    catchphrase: 'うるおいは、\nお湯から始まる。',
    category: '入浴剤',
    tags: ['保湿', '入浴剤', 'うるおい'],
    heroImage: '/images/neck-skin.png',
    relatedSlugs: ['dry-skin-bathsalt', 'bath-vs-topical-skincare', 'bath-as-serum'],
  },
  {
    slug: 'dry-after-bath',
    lp: 'lp2',
    title: 'お風呂上がりを、\n急がなくなった夜。',
    catchphrase: '乾燥を忘れる夜が、\nある。',
    category: 'スキンケア',
    tags: ['乾燥', 'お風呂上がり', '夜ケア'],
    heroImage: '/images/after-bath-exit.png',
    relatedSlugs: ['dry-skin-bathsalt', 'skincare-prep', 'morning-skin-bath'],
  },
  {
    slug: 'dry-season-bath',
    lp: 'lp2',
    title: '寒い夜に、\n帰りたくなるお風呂。',
    catchphrase: '冬の夜を、\nやさしくほどく。',
    category: '乾燥肌ケア',
    tags: ['冬ケア', '乾燥シーズン', 'バスタイム'],
    heroImage: '/images/winter-bath.png',
    relatedSlugs: ['dry-skin-bathsalt', 'bath-vs-topical-skincare', '30s-moisturize'],
  },
  {
    slug: 'makeup-bath',
    lp: 'lp2',
    title: '今夜のお風呂が、\n明日の顔をつくる。',
    catchphrase: 'メイク前の肌が、\n少し好きになる朝。',
    category: 'メイク',
    tags: ['化粧ノリ', 'バスタイム', '肌ベース'],
    heroImage: '/images/makeup-bath.png',
    relatedSlugs: ['night-beauty-routine', 'skincare-prep', 'morning-skin-bath'],
  },
  {
    slug: 'morning-skin-bath',
    lp: 'lp2',
    title: '朝の肌が、\n少し好きになる夜。',
    catchphrase: '昨夜のお風呂が、\n今朝の肌になっている。',
    category: 'スキンケア',
    tags: ['翌朝肌', '保湿', 'バスタイム'],
    heroImage: '/images/makeup-before.png',
    relatedSlugs: ['makeup-bath', 'night-beauty-routine', 'dry-after-bath'],
  },
  {
    slug: 'clear-skin-bath',
    lp: 'lp2',
    title: '朝の光まで、\n味方になる肌へ。',
    catchphrase: 'なんか今日、\n肌がいい気がする。',
    category: '美肌',
    tags: ['透明感', 'くすみ', 'お風呂'],
    heroImage: '/images/clear-skin-morning.png',
    relatedSlugs: ['skincare-prep', 'effortless-bath-beauty', 'dry-skin-bathsalt'],
  },
  {
    slug: 'bath-vs-topical-skincare',
    lp: 'lp2',
    title: 'お風呂上がりを、\n急がない夜へ。',
    catchphrase: 'スキンケアは、\nお風呂から始まっている。',
    category: 'スキンケア理論',
    tags: ['乾燥', '保湿', '浸かる美容'],
    heroImage: '/images/after-bath-towel.png',
    relatedSlugs: ['dry-skin-bathsalt', 'moisturizing-bathsalt', 'dry-after-bath'],
  },
  {
    slug: 'effortless-bath-beauty',
    lp: 'lp2',
    title: '頑張らなくてもいい美容を。',
    catchphrase: 'ただ浸かるだけで、\n整っていく。',
    category: '美容ライフスタイル',
    tags: ['簡単美容', '習慣', 'バスタイム'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['benefits-of-bath-beauty', 'morning-skin-bath', 'night-beauty-routine'],
  },
  {
    slug: 'night-beauty-routine',
    lp: 'lp2',
    title: '朝の化粧ノリが変わる、\n夜の美容習慣。',
    catchphrase: '夜に整う肌が、\n朝のメイクを楽にする。',
    category: 'メイク',
    tags: ['化粧ノリ', '夜ルーティン', '保湿'],
    heroImage: '/images/bath-texture.jpg',
    relatedSlugs: ['makeup-bath', 'morning-skin-bath', 'skincare-prep'],
  },
  {
    slug: 'benefits-of-bath-beauty',
    lp: 'lp2',
    title: 'お風呂美容は、\nなぜ続けやすいのか？',
    catchphrase: '毎日続くから、\n肌が変わる。',
    category: '美容習慣',
    tags: ['習慣化', 'お風呂美容', 'セルフケア'],
    heroImage: '/images/color-change.jpg',
    relatedSlugs: ['effortless-bath-beauty', 'bath-beauty-for-skin', 'morning-skin-bath'],
  },
  {
    slug: 'bath-beauty-for-skin',
    lp: 'lp2',
    title: 'お風呂美容を始めるなら、\nまず変えるべきこと。',
    catchphrase: 'お湯を変えると、\nすべてが変わる。',
    category: '美容習慣',
    tags: ['お風呂美容', '始め方', '入浴剤'],
    heroImage: '/images/bath-texture.jpg',
    relatedSlugs: ['change-your-water', 'moisturizing-bathsalt', 'benefits-of-bath-beauty'],
  },
  {
    slug: 'skincare-prep',
    lp: 'lp2',
    title: 'スキンケア前に、\n肌を"整える"という習慣。',
    catchphrase: '塗る前に、\n肌を整える。',
    category: 'スキンケア理論',
    tags: ['スキンケア', '入浴', '浸透'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['makeup-bath', 'dry-after-bath', 'morning-skin-bath'],
  },
  {
    slug: 'change-your-water',
    lp: 'lp2',
    title: 'スキンケアより先に、\n"お湯"を変えてみる。',
    catchphrase: '毎日触れるものほど、\n見直す価値がある。',
    category: '美肌',
    tags: ['お湯', 'シリカ', '美肌'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['bath-beauty-for-skin', 'benefits-of-bath-beauty', 'dry-skin-bathsalt'],
  },
  {
    slug: '30s-moisturize',
    lp: 'lp2',
    title: '30代からの保湿は、\n"浸かる美容"が鍵。',
    catchphrase: '30代の肌変化に、\nお風呂という答え。',
    category: '年齢肌',
    tags: ['30代', '年齢肌', '保湿'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['bath-vs-topical-skincare', 'effortless-bath-beauty', 'dry-season-bath'],
  },

  // ── LP未割り当て（LP2扱い）──────────────────────────
  {
    slug: 'dry-skin-bath',
    lp: 'lp2',
    title: '乾燥肌を守る、\n"浸かる保湿"という考え方',
    catchphrase: '乾燥肌こそ、\nお風呂を変えるべき理由がある。',
    category: '乾燥肌ケア',
    tags: ['乾燥肌', '入浴法', '保湿'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['dry-after-bath', 'dry-skin-bathsalt', 'bath-vs-topical-skincare'],
  },
  {
    slug: 'bath-salt-guide',
    lp: 'lp2',
    title: '後悔しない、\n美容入浴剤の選び方',
    catchphrase: '成分で選ぶ人だけが、\n手に入れる肌がある。',
    category: '入浴剤',
    tags: ['入浴剤', '成分', 'シリカ'],
    heroImage: '/images/butterfly-pea.jpg',
    relatedSlugs: ['moisturizing-bathsalt', 'dry-skin-bathsalt', 'dry-after-bath'],
  },
]

export function getArticleBySlug(slug) {
  const article = articles.find(a => a.slug === slug)
  if (!article) return null
  const related = article.relatedSlugs
    .map(s => articles.find(a => a.slug === s))
    .filter(Boolean)
    .map(({ slug, title, category }) => ({ slug, title, category }))
  return { ...article, relatedArticles: related }
}
