export const articles = [
  // ── 既存10記事 ──────────────────────────────────────
  {
    slug: 'dry-skin-bath',
    title: '乾燥肌を守る、\n"浸かる保湿"という考え方',
    catchphrase: '乾燥肌こそ、\nお風呂を変えるべき理由がある。',
    category: '乾燥肌ケア',
    tags: ['乾燥肌', '入浴法', '保湿'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['dry-after-bath', 'dry-skin-bathsalt', 'bath-vs-topical-skincare'],
  },
  {
    slug: 'dry-after-bath',
    title: 'お風呂上がり、\nなぜ肌は乾燥するのか？',
    catchphrase: '出た後の3分が、\n翌朝の肌を決める。',
    category: 'スキンケア',
    tags: ['乾燥', 'お風呂上がり', 'ケア'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['dry-skin-bath', 'skincare-prep', 'morning-skin-bath'],
  },
  {
    slug: 'bath-salt-guide',
    title: '後悔しない、\n美容入浴剤の選び方',
    catchphrase: '成分で選ぶ人だけが、\n手に入れる肌がある。',
    category: '入浴剤',
    tags: ['入浴剤', '成分', 'シリカ'],
    heroImage: '/images/butterfly-pea.jpg',
    relatedSlugs: ['moisturizing-bathsalt', 'dry-skin-bathsalt', 'bath-as-serum'],
  },
  {
    slug: 'change-your-water',
    title: 'スキンケアより先に、\n"お湯"を変えてみる。',
    catchphrase: '毎日触れるものほど、\n見直す価値がある。',
    category: '美肌',
    tags: ['お湯', 'シリカ', '美肌'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['bath-beauty-for-skin', 'bath-beauty-habit', 'benefits-of-bath-beauty'],
  },
  {
    slug: 'bath-beauty-habit',
    title: 'お風呂時間を、\n"整う美容時間"へ。',
    catchphrase: 'お風呂時間を、\nもっと整う時間へ。',
    category: '美容習慣',
    tags: ['習慣化', '肌変化', 'バス美容'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['effortless-bath-beauty', 'benefits-of-bath-beauty', 'morning-skin-bath'],
  },
  {
    slug: 'makeup-bath',
    title: '化粧ノリは、\nお風呂時間で変わる。',
    catchphrase: '翌朝の肌は、\n昨夜のバスタイムでできている。',
    category: 'メイク',
    tags: ['化粧ノリ', 'バスタイム', '肌ベース'],
    heroImage: '/images/bath-texture.jpg',
    relatedSlugs: ['night-beauty-routine', 'skincare-prep', 'morning-skin-bath'],
  },
  {
    slug: '30s-moisturize',
    title: '30代からの保湿は、\n"浸かる美容"が鍵。',
    catchphrase: '30代の肌変化に、\nお風呂という答え。',
    category: '年齢肌',
    tags: ['30代', '年齢肌', '保湿'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['bath-vs-topical-skincare', 'effortless-bath-beauty', 'dry-season-bath'],
  },
  {
    slug: 'skincare-prep',
    title: 'スキンケア前に、\n肌を"整える"という習慣。',
    catchphrase: '塗る前に、\n肌を整える。',
    category: 'スキンケア理論',
    tags: ['スキンケア', '入浴', '浸透'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['makeup-bath', 'dry-after-bath', 'bath-as-serum'],
  },
  {
    slug: 'beauty-women-bath',
    title: '美容意識の高い女性ほど、\nお風呂時間を大切にしている。',
    catchphrase: '美容を知る女性ほど、\nバスタイムにこだわる。',
    category: '美容ライフスタイル',
    tags: ['バスタイム', '美容習慣', 'セルフケア'],
    heroImage: '/images/bath-texture.jpg',
    relatedSlugs: ['effortless-bath-beauty', 'bath-as-serum', 'clear-skin-bath'],
  },
  {
    slug: 'bath-as-serum',
    title: '"浸かる美容液"という新習慣。',
    catchphrase: '"塗る"から"浸かる"へ。',
    category: 'トレンド美容',
    tags: ['浸かる美容液', '入浴剤', '全身スキンケア'],
    heroImage: '/images/color-change.jpg',
    relatedSlugs: ['bath-beauty-for-skin', 'moisturizing-bathsalt', 'skincare-prep'],
  },

  // ── 新規10記事（SEO最適化URL）──────────────────────
  {
    slug: 'dry-skin-bathsalt',
    title: '乾燥肌の人が、\n入浴剤選びで見るべきこと。',
    catchphrase: 'お湯の質が、\n乾燥肌の未来を変える。',
    category: '乾燥肌ケア',
    tags: ['乾燥肌', '入浴剤', 'シリカ'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['dry-skin-bath', 'moisturizing-bathsalt', 'bath-vs-topical-skincare'],
  },
  {
    slug: 'moisturizing-bathsalt',
    title: '保湿系入浴剤は、\n何が違うのか？',
    catchphrase: '成分を知ると、\nお湯の選び方が変わる。',
    category: '入浴剤',
    tags: ['保湿', '入浴剤', '成分比較'],
    heroImage: '/images/butterfly-pea.jpg',
    relatedSlugs: ['dry-skin-bathsalt', 'bath-salt-guide', 'bath-as-serum'],
  },
  {
    slug: 'bath-beauty-for-skin',
    title: 'お風呂美容を始めるなら、\nまず変えるべきこと。',
    catchphrase: 'お湯を変えると、\nすべてが変わる。',
    category: '美容習慣',
    tags: ['お風呂美容', '始め方', '入浴剤'],
    heroImage: '/images/bath-texture.jpg',
    relatedSlugs: ['change-your-water', 'bath-as-serum', 'benefits-of-bath-beauty'],
  },
  {
    slug: 'clear-skin-bath',
    title: '透明感のある肌を目指す人が、\nお風呂時間を大切にする理由。',
    catchphrase: '透明感は、\n内側から整えるもの。',
    category: '美肌',
    tags: ['透明感', 'くすみ', 'お風呂'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['beauty-women-bath', 'skincare-prep', 'effortless-bath-beauty'],
  },
  {
    slug: 'bath-vs-topical-skincare',
    title: '"塗る保湿"だけでは、\n追いつかない夜へ。',
    catchphrase: '浸かる美容は、\n届く場所が違う。',
    category: 'スキンケア理論',
    tags: ['乾燥', '保湿', '浸かる美容'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['dry-skin-bath', 'bath-as-serum', 'dry-skin-bathsalt'],
  },
  {
    slug: 'effortless-bath-beauty',
    title: '頑張らなくてもいい美容を。',
    catchphrase: 'ただ浸かるだけで、\n整っていく。',
    category: '美容ライフスタイル',
    tags: ['簡単美容', '習慣', 'バスタイム'],
    heroImage: '/images/blue-bath.jpg',
    relatedSlugs: ['benefits-of-bath-beauty', 'bath-beauty-habit', 'morning-skin-bath'],
  },
  {
    slug: 'morning-skin-bath',
    title: '翌朝の肌が、\n少し楽しみになる入浴時間。',
    catchphrase: '昨夜のお風呂が、\n今朝の肌になっている。',
    category: 'スキンケア',
    tags: ['翌朝肌', '保湿', 'バスタイム'],
    heroImage: '/images/bath-texture.jpg',
    relatedSlugs: ['makeup-bath', 'night-beauty-routine', 'dry-after-bath'],
  },
  {
    slug: 'dry-season-bath',
    title: '乾燥する季節こそ、\n入浴時間を見直す。',
    catchphrase: '季節が変わるたびに、\nお風呂が答えをくれる。',
    category: '乾燥肌ケア',
    tags: ['乾燥シーズン', '冬ケア', '保湿'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['dry-skin-bath', 'bath-vs-topical-skincare', '30s-moisturize'],
  },
  {
    slug: 'night-beauty-routine',
    title: '朝の化粧ノリが変わる、\n夜の美容習慣。',
    catchphrase: '夜に整う肌が、\n朝のメイクを楽にする。',
    category: 'メイク',
    tags: ['化粧ノリ', '夜ルーティン', '保湿'],
    heroImage: '/images/bath-texture.jpg',
    relatedSlugs: ['makeup-bath', 'morning-skin-bath', 'skincare-prep'],
  },
  {
    slug: 'benefits-of-bath-beauty',
    title: 'お風呂美容は、\nなぜ続けやすいのか？',
    catchphrase: '毎日続くから、\n肌が変わる。',
    category: '美容習慣',
    tags: ['習慣化', 'お風呂美容', 'セルフケア'],
    heroImage: '/images/color-change.jpg',
    relatedSlugs: ['effortless-bath-beauty', 'bath-beauty-habit', 'bath-beauty-for-skin'],
  },
]

export function getArticleBySlug(slug) {
  const article = articles.find(a => a.slug === slug)
  if (!article) return null
  const related = article.relatedSlugs
    .map(s => articles.find(a => a.slug === s))
    .filter(Boolean)
    .map(({ slug, title, category }) => ({ slug, title, category }))
  return { ...article, relatedArticles: related }
}
