export const articles = [
  // ── LP3（北欧スパ世界観 / Blue Lagoon文脈）────────────
  {
    slug: 'blue-lagoon-world',
    lp: 'lp3',
    title: 'ブルーラグーンが、\n世界中の人を惹きつける理由。',
    catchphrase: '青い水の前で、\n人は静かになる。',
    description: 'アイスランドのブルーラグーンがなぜ青いのか、その秘密はシリカにある。世界中の人を惹きつける乳青色の温泉の世界観と、自宅でその感覚を味わう方法とは。',
    category: '北欧スパ文化',
    tags: ['ブルーラグーン', 'アイスランド温泉', 'ブルーラグーンなぜ青い', '青い温泉', 'シリカ温泉', '乳青色温泉', 'ブルーラグーン自宅'],
    heroImage: '/images/blue-bath.png',
    relatedSlugs: ['why-bath-turns-blue', 'milky-blue-world', 'luxury-spa-silence'],
  },
  {
    slug: 'why-bath-turns-blue',
    lp: 'lp3',
    title: 'なぜ、お湯は乳青色に\n変わるのか。',
    catchphrase: '透明なお湯が、\n幻想的な青に変わる瞬間。',
    description: 'なぜお風呂のお湯が青くなるのか。乳青色・ミルキーブルーが生まれる理由はシリカにある。青いお湯・青い温泉・ブルーラグーンなぜ青いかを、3つの理由でやさしく解説します。',
    category: '温泉文化',
    tags: ['お風呂 青くなる', '乳青色', 'シリカ', '青いお湯', 'ブルーラグーン なぜ青い', '青い温泉', 'アイスランド 温泉', 'シリカ 温泉'],
    heroImage: '/images/color-change.jpg',
    relatedSlugs: ['blue-lagoon-world', 'milky-blue-world', 'home-spa-experience'],
  },
  {
    slug: 'home-spa-experience',
    lp: 'lp3',
    title: '自宅に、\n静かなスパをつくる。',
    catchphrase: '特別な場所に行かなくても、\n非日常はつくれる。',
    category: '自宅スパ',
    tags: ['自宅スパ', 'おうちスパ', 'バスタイム演出'],
    heroImage: '/images/quiet-bath.png',
    relatedSlugs: ['tired-night-bath', 'reward-bath-habit', 'bath-as-experience'],
  },
  {
    slug: 'nordic-bath-culture',
    lp: 'lp3',
    title: '北欧の人は、\n回復する時間を知っている。',
    catchphrase: '静かな回復が、\n文化になっている国。',
    description: '北欧のスパ・サウナ文化に共通する「何もしない時間」の価値。静かな回復という北欧のライフスタイルは、私たちの日常にも必要かもしれない。今夜のお風呂時間から始める、静かな回復の習慣。',
    category: '北欧ライフスタイル',
    tags: ['北欧スパ', '北欧ライフスタイル', '温浴文化'],
    heroImage: '/images/bath-surface.jpg',
    relatedSlugs: ['blue-lagoon-world', 'luxury-spa-silence', 'tired-night-bath'],
  },
  {
    slug: 'tired-night-bath',
    lp: 'lp3',
    title: '疲れた夜ほど、\nお風呂時間を変えたくなる。',
    catchphrase: '疲れた夜ほど、\nお風呂が特別になる。',
    category: '夜時間',
    tags: ['夜時間', 'バスタイム', '疲れの癒し'],
    heroImage: '/images/calm-time.png',
    relatedSlugs: ['reward-bath-habit', 'bath-as-experience', 'home-spa-experience'],
  },
  {
    slug: 'milky-blue-world',
    lp: 'lp3',
    title: 'ミルキーブルーの世界が、\n人を惹きつける理由。',
    catchphrase: '乳青色に包まれた瞬間、\n静かになれる。',
    description: 'ミルキーブルーとは、青に白が溶け込んだような乳青色のこと。ブルーラグーンのような青い温泉が人を惹きつける理由と、青いお風呂・青い入浴剤で自宅のお風呂をミルキーブルーのリラックス空間にする方法。',
    category: '世界観',
    tags: ['ミルキーブルー', '乳青色', '青いお風呂', '青い入浴剤', 'ミルキーブルー 入浴', 'リラックス お風呂', 'お風呂 癒し', 'ブルーラグーン', '青い温泉'],
    heroImage: '/images/dissolving.png',
    relatedSlugs: ['blue-lagoon-world', 'why-bath-turns-blue', 'why-blue-water'],
  },
  {
    slug: 'reward-bath-habit',
    lp: 'lp3',
    title: '「ご褒美時間」をつくる、\n入浴という習慣。',
    catchphrase: '何かを買わなくても、\n今夜は特別にできる。',
    category: 'ご褒美バスタイム',
    tags: ['ご褒美', 'バスタイム', '夜ルーティン'],
    heroImage: '/images/quiet-bath-2.png',
    relatedSlugs: ['tired-night-bath', 'bath-as-experience', 'home-spa-experience'],
  },
  {
    slug: 'luxury-spa-silence',
    lp: 'lp3',
    title: '海外のラグジュアリースパに\n共通する、静けさ。',
    catchphrase: '贅沢とは、静かに\n何かに包まれることだ。',
    category: 'ラグジュアリースパ',
    tags: ['ラグジュアリースパ', '高級ホテルスパ', '静けさ'],
    heroImage: '/images/cta-water-surface.png',
    relatedSlugs: ['nordic-bath-culture', 'blue-lagoon-world', 'why-blue-water'],
  },
  {
    slug: 'why-blue-water',
    lp: 'lp3',
    title: 'なぜ人は、\n「青い水」に惹かれるのか。',
    catchphrase: '青い水に浸かることは、\n自分に戻ることだ。',
    description: 'なぜ水は青く見えるのか。光の散乱と光の反射による理由を解説。さらに、なぜ青い水は美しく人を惹きつけるのかを心理・感覚の面から掘り下げます。ブルーラグーンの乳青色・ミルキーブルーを自宅の青いお風呂で体験する方法も。',
    category: '感覚・心理',
    tags: ['水 なぜ青い', '青い水 理由', '青い温泉', 'ブルーラグーン 青い理由', '光の散乱', '光の反射', '乳青色', 'ミルキーブルー', '青いお風呂', '青い入浴剤'],
    heroImage: '/images/column-hero.png',
    relatedSlugs: ['milky-blue-world', 'why-bath-turns-blue', 'blue-lagoon-world'],
  },
  {
    slug: 'bath-as-experience',
    lp: 'lp3',
    title: 'お風呂を、「作業」から\n「体験」へ変える。',
    catchphrase: '毎日のお風呂が、\n毎日の体験になる。',
    category: '体験デザイン',
    tags: ['没入感', '体験', 'バスタイム'],
    heroImage: '/images/quiet-bath.png',
    relatedSlugs: ['tired-night-bath', 'reward-bath-habit', 'home-spa-experience'],
  },

  // ── LP1（ブランド・世界観）──────────────────────────
  {
    slug: 'bath-beauty-habit',
    lp: 'lp1',
    title: 'お風呂時間を、\n"整う美容時間"へ。',
    catchphrase: 'お風呂時間を、\nもっと整う時間へ。',
    category: '美容習慣',
    tags: ['習慣化', '肌変化', 'バス美容'],
    heroImage: '/images/bath-scene.png',
    relatedSlugs: ['beauty-women-bath', 'bath-as-serum', 'effortless-bath-beauty'],
  },
  {
    slug: 'beauty-women-bath',
    lp: 'lp1',
    title: '美容意識の高い女性ほど、\nお風呂時間を大切にしている。',
    catchphrase: '美容を知る女性ほど、\nバスタイムにこだわる。',
    category: '美容ライフスタイル',
    tags: ['バスタイム', '美容習慣', 'セルフケア'],
    heroImage: '/images/morning-bath.png',
    relatedSlugs: ['bath-as-serum', 'bath-beauty-habit', 'effortless-bath-beauty'],
  },
  {
    slug: 'bath-as-serum',
    lp: 'lp1',
    title: '"浸かる美容液"という新習慣。',
    catchphrase: '"塗る"から"浸かる"へ。',
    category: 'トレンド美容',
    tags: ['浸かる美容液', '入浴剤', '全身スキンケア'],
    heroImage: '/images/bath-closeup.png',
    relatedSlugs: ['bath-beauty-habit', 'beauty-women-bath', 'moisturizing-bathsalt'],
  },

  // ── LP2（美肌・保湿）────────────────────────────────
  {
    slug: 'dry-skin-bathsalt',
    lp: 'lp2',
    title: '乾燥肌の人が、\n入浴剤選びで見るべきこと。',
    catchphrase: 'お湯の質が、\n乾燥肌の未来を変える。',
    category: '乾燥肌ケア',
    tags: ['乾燥肌', '入浴剤', 'シリカ'],
    heroImage: '/images/bath-scene-3.png',
    relatedSlugs: ['moisturizing-bathsalt', 'dry-after-bath', 'bath-vs-topical-skincare'],
  },
  {
    slug: 'moisturizing-bathsalt',
    lp: 'lp2',
    title: '保湿入浴剤を変えたら、\n夜が静かになった。',
    catchphrase: 'うるおいは、\nお湯から始まる。',
    category: '入浴剤',
    tags: ['保湿', '入浴剤', 'うるおい'],
    heroImage: '/images/neck-skin.png',
    relatedSlugs: ['dry-skin-bathsalt', 'bath-vs-topical-skincare', 'bath-as-serum'],
  },
  {
    slug: 'dry-after-bath',
    lp: 'lp2',
    title: 'お風呂上がりを、\n急がなくなった夜。',
    catchphrase: '乾燥を忘れる夜が、\nある。',
    category: 'スキンケア',
    tags: ['乾燥', 'お風呂上がり', '夜ケア'],
    heroImage: '/images/after-bath-exit.png',
    relatedSlugs: ['dry-skin-bathsalt', 'skincare-prep', 'morning-skin-bath'],
  },
  {
    slug: 'dry-season-bath',
    lp: 'lp2',
    title: '寒い夜に、\n帰りたくなるお風呂。',
    catchphrase: '冬の夜を、\nやさしくほどく。',
    category: '乾燥肌ケア',
    tags: ['冬ケア', '乾燥シーズン', 'バスタイム'],
    heroImage: '/images/winter-bath.png',
    relatedSlugs: ['dry-skin-bathsalt', 'bath-vs-topical-skincare', '30s-moisturize'],
  },
  {
    slug: 'makeup-bath',
    lp: 'lp2',
    title: '今夜のお風呂が、\n明日の顔をつくる。',
    catchphrase: 'メイク前の肌が、\n少し好きになる朝。',
    category: 'メイク',
    tags: ['化粧ノリ', 'バスタイム', '肌ベース'],
    heroImage: '/images/makeup-bath.png',
    relatedSlugs: ['night-beauty-routine', 'skincare-prep', 'morning-skin-bath'],
  },
  {
    slug: 'morning-skin-bath',
    lp: 'lp2',
    title: '朝の肌が、\n少し好きになる夜。',
    catchphrase: '昨夜のお風呂が、\n今朝の肌になっている。',
    category: 'スキンケア',
    tags: ['翌朝肌', '保湿', 'バスタイム'],
    heroImage: '/images/makeup-before.png',
    relatedSlugs: ['makeup-bath', 'night-beauty-routine', 'dry-after-bath'],
  },
  {
    slug: 'clear-skin-bath',
    lp: 'lp2',
    title: '朝の光まで、\n味方になる肌へ。',
    catchphrase: 'なんか今日、\n肌がいい気がする。',
    category: '美肌',
    tags: ['透明感', 'くすみ', 'お風呂'],
    heroImage: '/images/clear-skin-morning.png',
    relatedSlugs: ['skincare-prep', 'effortless-bath-beauty', 'dry-skin-bathsalt'],
  },
  {
    slug: 'bath-vs-topical-skincare',
    lp: 'lp2',
    title: 'お風呂上がりを、\n急がない夜へ。',
    catchphrase: 'スキンケアは、\nお風呂から始まっている。',
    category: 'スキンケア理論',
    tags: ['乾燥', '保湿', '浸かる美容'],
    heroImage: '/images/after-bath-towel.png',
    relatedSlugs: ['dry-skin-bathsalt', 'moisturizing-bathsalt', 'dry-after-bath'],
  },
  {
    slug: 'effortless-bath-beauty',
    lp: 'lp2',
    title: '頑張らなくても、\n整ってる。',
    catchphrase: '美容に追われない、\n夜へ。',
    category: '美容ライフスタイル',
    tags: ['簡単美容', '習慣', 'バスタイム'],
    heroImage: '/images/effortless-beauty.png',
    relatedSlugs: ['benefits-of-bath-beauty', 'morning-skin-bath', 'night-beauty-routine'],
  },
  {
    slug: 'night-beauty-routine',
    lp: 'lp2',
    title: '一日を静かに\n終える時間へ。',
    catchphrase: '美容より先に、\nちゃんと休む夜へ。',
    category: 'メイク',
    tags: ['化粧ノリ', '夜ルーティン', '保湿'],
    heroImage: '/images/relax-night.png',
    relatedSlugs: ['makeup-bath', 'morning-skin-bath', 'skincare-prep'],
  },
  {
    slug: 'benefits-of-bath-beauty',
    lp: 'lp2',
    title: 'お風呂時間が、\n暮らしまで整える。',
    catchphrase: 'なんか調子いい、\nそんな夜へ。',
    category: '美容習慣',
    tags: ['習慣化', 'お風呂美容', 'セルフケア'],
    heroImage: '/images/totonou-woman.png',
    relatedSlugs: ['effortless-bath-beauty', 'bath-beauty-for-skin', 'morning-skin-bath'],
  },
  {
    slug: 'bath-beauty-for-skin',
    lp: 'lp2',
    title: '肌がラクな夜は、\n気持ちもラク。',
    catchphrase: '今日は、\n肌がちゃんと静か。',
    category: '美容習慣',
    tags: ['お風呂美容', '始め方', '入浴剤'],
    heroImage: '/images/calm-time.png',
    relatedSlugs: ['change-your-water', 'moisturizing-bathsalt', 'benefits-of-bath-beauty'],
  },
  {
    slug: 'skincare-prep',
    lp: 'lp2',
    title: 'お風呂後の肌は、\n少しやさしい。',
    catchphrase: '整った肌には、\nちゃんと届く。',
    category: 'スキンケア理論',
    tags: ['スキンケア', '入浴', '浸透'],
    heroImage: '/images/skincare-moment.png',
    relatedSlugs: ['makeup-bath', 'dry-after-bath', 'morning-skin-bath'],
  },
  {
    slug: 'change-your-water',
    lp: 'lp2',
    title: 'お湯が変わると、\n夜が変わる。',
    catchphrase: '今日のお湯、\nなんかやさしい。',
    category: '美肌',
    tags: ['お湯', 'シリカ', '美肌'],
    heroImage: '/images/quiet-bath.png',
    relatedSlugs: ['bath-beauty-for-skin', 'benefits-of-bath-beauty', 'dry-skin-bathsalt'],
  },
  {
    slug: '30s-moisturize',
    lp: 'lp2',
    title: '乾燥しない夜が、\n肌をラクにする。',
    catchphrase: '今日は、\n肌がちゃんと落ち着いてる。',
    category: '年齢肌',
    tags: ['30代', '年齢肌', '保湿'],
    heroImage: '/images/stress-zero.png',
    relatedSlugs: ['bath-vs-topical-skincare', 'effortless-bath-beauty', 'dry-season-bath'],
  },

  // ── LP未割り当て（LP2扱い）──────────────────────────
  {
    slug: 'dry-skin-bath',
    lp: 'lp2',
    title: 'お風呂後、\n肌がちゃんと落ち着いてる。',
    catchphrase: '乾燥しない夜は、\n気持ちまで少し静か。',
    category: '乾燥肌ケア',
    tags: ['乾燥肌', '入浴法', '保湿'],
    heroImage: '/images/stress-free.png',
    relatedSlugs: ['dry-after-bath', 'dry-skin-bathsalt', 'bath-vs-topical-skincare'],
  },
  {
    slug: 'bath-salt-guide',
    lp: 'lp2',
    title: '今日のお風呂、\nちょっと楽しみ。',
    catchphrase: 'お湯を変えると、\n夜も変わる。',
    category: '入浴剤',
    tags: ['入浴剤', '成分', 'シリカ'],
    heroImage: '/images/butterfly-pea.jpg',
    relatedSlugs: ['moisturizing-bathsalt', 'dry-skin-bathsalt', 'dry-after-bath'],
  },
]

export function getArticleBySlug(slug) {
  const article = articles.find(a => a.slug === slug)
  if (!article) return null
  const related = article.relatedSlugs
    .map(s => articles.find(a => a.slug === s))
    .filter(Boolean)
    .map(({ slug, title, category }) => ({ slug, title, category }))
  return { ...article, relatedArticles: related }
}
